### PR TITLE
Raku rename

### PR DESCRIPTION
**Pull request by bduggan**
I'm opening this PR for the Perl 6 to Raku name change.

This draws on #53 but has a few modifications.

### CODE REVIEW

**Comment by tinmarino** [comment]
Just a troubleshooter for people having problem to update to `raku` on debian

To get the lastest version on __Debian__ see [rakudo-pkg](https://github.com/nxadm/rakudo-pkg#os-repositories) : I had troubles to bootstrap with [Z](https://github.com/perl6/z) because I messed all my binaries, the last link restored peace on __Intel__ or __AMD__ 

```bash
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61
echo "deb https://dl.bintray.com/nxadm/rakudo-pkg-debs `lsb_release -cs` main" | sudo tee -a /etc/apt/sources.list.d/rakudo-pkg.list
sudo apt-get update && sudo apt-get install rakudo-pkg
```

PS : My initial error before unwinding that was on [Net::ZMQ4](https://github.com/arnsholt/Net-ZMQ)

```
Cannot find method 'is_dispatcher' on 'BOOTCode': no method cache and no .^find_method
home#sources/FC1DE5470FF5B7D8A301F6A4F740D2AB33836E50 (Net::ZMQ4::Context):5
home#sources/542A37D8381253B57190B2E0A2580627D9EB8B49 (Net::ZMQ4):6
```

Aposteriori it was a permission problem (root Vs user install) : I reinstalled all modules in `~/.raku` (user) so I will be happy for 100 years (or maybe days).
Take care of the RAKUDODIR hardcoded in Z

In my bashrc
```bash
export PATH=$HOME/.raku/share/perl6/site/bin/:$PATH    # zef and jupyter-kernel.raku
export PATH=$HOME/.raku/bin:$PATH
```

**Comment by tinmarino** [comment]
We should have done a __Renaming day__ but someone has to start. So I support 200% your initiative @bduggan.
Time for me to go to [pygment](https://github.com/pygments/pygments) and ask for perl6 -> raku to get color.

```
.local/lib/python3.7/site-packages/jupyter_console/ptshell.py:117: UserWarning: No lexer found for language 'raku'. Treating as plain text.
  warn("No lexer found for language %r. Treating as plain text." % name)
Jupyter console 6.1.1dev

Welcome to Raku (rakudo 2020.02.1.205.g.78371.bb.0.c).
```

**Comment by bduggan** [comment]
Thanks for looking into this @tinmarino.  I was wondering about the error message.  Currently with `pip install pygments --upgrade` I get pygments version 2.5.2, and with `pip3 install pygments --upgrade` I get 2.6.1 (or even `pip3 install git+git://github.com/pygments/pygments --upgrade` doesn't seem to help) -- have you had success installing a version that works?

**Comment by tinmarino** [comment]
It works here. Strangely my version is also `2.6.1` and `pip3 install git+git://github.com/pygments/pygments --upgrade --force-install` should have worked. Maybe add the `--force-install` because the first `2.6.1` release may be old.

**Comment by bduggan** [comment]
Reinstalling jupyter with pip3 (instead of pip) fixed it :-)

**Pull request merged**
