### PR TITLE
Trap sigint instead of hanging

### PR DESCRIPTION
**Pull request by bduggan**
This should help with #75

### CODE REVIEW

**Comment by bduggan** [comment]
This does run code on another thread.  Are there any potential negative side effects?

**Comment by tinmarino** [comment]
Awesome, you did it! As far as I know, on this kernel and ipykernel supports `Ctrl-C`.

What I get:
```
In [1]: sleep 3                              
^CTrapped interrupt.  Please restart the kernel to abort execution.Out[1]: [got sigint on thread 13
```

Could you and a `\n`:
```
{ :text("Trapped interrupt.  Please restart the kernel to abort execution.(---> \n <--- HERE)"),

**Comment by tinmarino** [comment]
As for the side effects. I thought about it and anyway `Ctrl-C` default behavior was to kill the kernel leaving a pending useless client. So it cannot be worse to have just one pending thread (usually blocked anyway).

We can see then with:
```raku
for 1..10  { .say; sleep 1; }
```
Keeping on looping but you advise it in the message.
As for 
```raku
start for 1..10  { .say; sleep 1; }
```
It cannot be killed but we spoke about it already. Maybe ipykernel have the same limitation.

**Comment by bduggan** [comment]
Sure -- added a `\n` 🙂  -- looks better now.

**Pull request merged**
